event.dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

order.service:
    class: MS\ExamplePHP\ObserverPattern\Service\OrderService
    arguments:
        - "@event.dispatcher"
        - "@logger"
#tags:
#    - { name: kernel.event_listener, event: event-check, method: checkEvent, priority }
